/* include/rudiments/private/config.h.  Generated by configure.  */
/* include/rudiments/private/config.h.in.  Generated from configure.in by autoheader.  */

/* Use inline functions or not */
/* #undef ENABLE_RUDIMENTS_INLINES */

/* getsockopt takes a void * on most systems */
#define GETSOCKOPT_OPTVAL_TYPE void *

/* Some systems use _timezone instead of timezone */
#define HAS_TIMEZONE 1

/* Some systems define tm_gmtoff in their struct tm */
#define HAS_TM_GMTOFF 1

/* Some systems define tm_name in their struct tm */
/* #undef HAS_TM_NAME */

/* Some systems define tm_tzadj in their struct tm */
/* #undef HAS_TM_TZADJ */

/* Some systems define tm_zone in their struct tm */
#define HAS_TM_ZONE 1

/* Some systems define __tm_gmtoff in their struct tm */
/* #undef HAS___TM_GMTOFF */

/* Some systems define __tm_zone in their struct tm */
/* #undef HAS___TM_ZONE */

/* Some systems have arpa/inet.h */
#define HAVE_ARPA_INET_H 1

/* Some systems don't have st_blocks in struct stat */
#define HAVE_BLKCNT_T 1

/* Some systems don't have st_blksize in struct stat */
#define HAVE_BLKSIZE_T 1

/* Some systems have bswap_64 */
#define HAVE_BSWAP_64 1

/* Some systems have byteswap.h */
#define HAVE_BYTESWAP_H 1

/* Some systems have clearenv */
#define HAVE_CLEARENV 1

/* Some systems have clock_nanosleep */
#define HAVE_CLOCK_NANOSLEEP 1

/* Some systems have CMSG_LEN */
#define HAVE_CMSG_LEN 1

/* Some systems have CMSG_SPACE */
#define HAVE_CMSG_SPACE 1

/* Most systems have ftok(const char *, int) */
#define HAVE_CONST_CHAR_FTOK 1

/* Some systems have CreateFileMapping */
/* #undef HAVE_CREATE_FILE_MAPPING */

/* CreateMutex function exists */
/* #undef HAVE_CREATE_MUTEX */

/* Some systems have crypt */
#define HAVE_CRYPT 1

/* Some systems have crypt.h */
#define HAVE_CRYPT_H 1

/* Some systems have crypt_r */
#define HAVE_CRYPT_R 1

/* Cygwin style statfs */
/* #undef HAVE_CYGWIN_STATFS */

/* Darwin style statfs */
/* #undef HAVE_DARWIN_STATFS */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Some systems define environ in unistd.h */
#define HAVE_ENVIRON 1

/* Some systems have fcntl */
#define HAVE_FCNTL 1

/* Some systems have fdatasync */
#define HAVE_FDATASYNC 1

/* FreeBSD style statfs */
/* #undef HAVE_FREEBSD_STATFS */

/* Most systems have ftok() */
#define HAVE_FTOK 1

/* Some systems have getaddrinfo */
#define HAVE_GETADDRINFO 1

/* Some systems have getgrgid_r */
#define HAVE_GETGRGID_R 1

/* Some systems have getgrgid_r */
/* #undef HAVE_GETGRGID_R_4 */

/* Some systems have getgrgid_r */
#define HAVE_GETGRGID_R_5 1

/* Some systems have getgrnam_r */
#define HAVE_GETGRNAM_R 1

/* Some systems have getgrnam_r */
/* #undef HAVE_GETGRNAM_R_4 */

/* Some systems have getgrnam_r */
#define HAVE_GETGRNAM_R_5 1

/* Some systems have gethostbyaddr_r */
#define HAVE_GETHOSTBYADDR_R 1

/* Some systems have gethostbyaddr_r */
/* #undef HAVE_GETHOSTBYADDR_R_7 */

/* Some systems have gethostbyaddr_r */
#define HAVE_GETHOSTBYADDR_R_8 1

/* Some systems have gethostbyname_r */
#define HAVE_GETHOSTBYNAME_R 1

/* Some systems have gethostbyname_r */
/* #undef HAVE_GETHOSTBYNAME_R_5 */

/* Some systems have gethostbyname_r */
#define HAVE_GETHOSTBYNAME_R_6 1

/* Some systems have getprotobyname_r */
#define HAVE_GETPROTOBYNAME_R 1

/* Some systems have getprotobyname_r */
/* #undef HAVE_GETPROTOBYNAME_R_4 */

/* Some systems have getprotobyname_r */
#define HAVE_GETPROTOBYNAME_R_5 1

/* Some systems have getprotobynumber_r */
#define HAVE_GETPROTOBYNUMBER_R 1

/* Some systems have getprotobynumber_r */
/* #undef HAVE_GETPROTOBYNUMBER_R_4 */

/* Some systems have getprotobynumber_r */
#define HAVE_GETPROTOBYNUMBER_R_5 1

/* Some systems have getpwnam_r */
#define HAVE_GETPWNAM_R 1

/* Some systems have getpwnam_r */
/* #undef HAVE_GETPWNAM_R_4 */

/* Some systems have getpwnam_r */
#define HAVE_GETPWNAM_R_5 1

/* Some systems have getpwuid_r */
#define HAVE_GETPWUID_R 1

/* Some systems have getpwuid_r */
/* #undef HAVE_GETPWUID_R_4 */

/* Some systems have getpwuid_r */
#define HAVE_GETPWUID_R_5 1

/* Some systems have getrpcbyname */
/* #undef HAVE_GETRPCBYNAME */

/* Some systems have getrpcbyname_r */
#define HAVE_GETRPCBYNAME_R 1

/* Some systems have getrpcbyname_r */
/* #undef HAVE_GETRPCBYNAME_R_4 */

/* Some systems have getrpcbyname_r */
#define HAVE_GETRPCBYNAME_R_5 1

/* Some systems have getrpcbynumber */
/* #undef HAVE_GETRPCBYNUMBER */

/* Some systems have getrpcbynumber_r */
#define HAVE_GETRPCBYNUMBER_R 1

/* Some systems have getrpcbynumber_r */
/* #undef HAVE_GETRPCBYNUMBER_R_4 */

/* Some systems have getrpcbynumber_r */
#define HAVE_GETRPCBYNUMBER_R_5 1

/* Some systems have getservbyname_r */
#define HAVE_GETSERVBYNAME_R 1

/* Some systems have getservbyname_r */
/* #undef HAVE_GETSERVBYNAME_R_5 */

/* Some systems have getservbyname_r */
#define HAVE_GETSERVBYNAME_R_6 1

/* Some systems have getservbyport_r */
#define HAVE_GETSERVBYPORT_R 1

/* Some systems have getservbyport_r */
/* #undef HAVE_GETSERVBYPORT_R_5 */

/* Some systems have getservbyport_r */
#define HAVE_GETSERVBYPORT_R_6 1

/* Some systems have getspnam_r */
#define HAVE_GETSPNAM_R 1

/* Some systems have getspnam_r */
/* #undef HAVE_GETSPNAM_R_4 */

/* Some systems have getspnam_r */
#define HAVE_GETSPNAM_R_5 1

/* Some systems have GetSystemTime */
/* #undef HAVE_GETSYSTEMTIME */

/* Some systems have inttypes.h */
#define HAVE_INTTYPES_H 1

/* Some systems have ioctl */
#define HAVE_IOCTL 1

/* Some systems have io.h */
/* #undef HAVE_IO_H */

/* Linux style statfs */
#define HAVE_LINUX_STATFS 1

/* Some systems have localtime_r */
#define HAVE_LOCALTIME_R 1

/* Some systems have lrand48 */
#define HAVE_LRAND48 1

/* Some systems have machine/endian.h */
/* #undef HAVE_MACHINE_ENDIAN_H */

/* Some systems have madvise */
#define HAVE_MADVISE 1

/* Some systems use caddr_t argument for madvise */
/* #undef HAVE_MADVISE_CADDR_T */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Some systems have mincore */
#define HAVE_MINCORE 1

/* Some systems use caddr_t argument for mincore */
/* #undef HAVE_MINCORE_CADDR_T */

/* Some systems have mincore with char argument */
/* #undef HAVE_MINCORE_CHAR */

/* Some systems have mincore with unsigned char argument */
#define HAVE_MINCORE_UCHAR 1

/* Some systems have mktime */
#define HAVE_MKTIME 1

/* Some systems have mlock */
#define HAVE_MLOCK 1

/* Some systems have mlockall */
#define HAVE_MLOCKALL 1

/* Some systems use caddr_t argument for mlock */
/* #undef HAVE_MLOCK_CADDR_T */

/* Some systems have mmap */
#define HAVE_MMAP 1

/* Some systems have mprotect */
#define HAVE_MPROTECT 1

/* Some systems use caddr_t argument for mprotect */
/* #undef HAVE_MPROTECT_CADDR_T */

/* Some msghdr structs have a msg_controllen member */
#define HAVE_MSGHDR_MSG_CONTROLLEN 1

/* Some msghdr structs have a msg_flags member */
#define HAVE_MSGHDR_MSG_FLAGS 1

/* Some systems have msync */
#define HAVE_MSYNC 1

/* Some systems use caddr_t argument for msync */
/* #undef HAVE_MSYNC_CADDR_T */

/* Some systems have munlock */
#define HAVE_MUNLOCK 1

/* Some systems have munlockall */
#define HAVE_MUNLOCKALL 1

/* Some systems use caddr_t argument for munlock */
/* #undef HAVE_MUNLOCK_CADDR_T */

/* Some systems use caddr_t argument for munmap */
/* #undef HAVE_MUNMAP_CADDR_T */

/* Some systems have nanosleep */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* NetBSD style statfs */
/* #undef HAVE_NETBSD_STATFS */

/* NetBSD-3.0 style statvfs */
/* #undef HAVE_NETBSD_STATVFS */

/* Some systems have netdb.h */
#define HAVE_NETDB_H 1

/* Some systems have netinet/in.h */
#define HAVE_NETINET_IN_H 1

/* Some systems have netinet/tcp.h */
#define HAVE_NETINET_TCP_H 1

/* Some systems define _NSGetEnviron in crt_externs.h */
/* #undef HAVE_NSGETENVIRON */

/* OpenBSD style statfs */
/* #undef HAVE_OPENBSD_STATFS */

/* Some systems have posix_fadvise */
#define HAVE_POSIX_FADVISE 1

/* Some systems have posix_fallocate */
#define HAVE_POSIX_FALLOCATE 1

/* Some systems have pselect */
#define HAVE_PSELECT 1

/* pthread_mutex_t type exists */
#define HAVE_PTHREAD_MUTEX_T 1

/* Some systems have putenv */
#define HAVE_PUTENV 1

/* Some systems have rand */
#define HAVE_RAND 1

/* Some systems have rand_r */
#define HAVE_RAND_R 1

/* Some systems have readdir_r */
#define HAVE_READDIR_R 1

/* Some systems have regcomp */
/* #undef HAVE_REGCOMP */

/* Some systems have rpc/rpcent.h */
/* #undef HAVE_RPCENT_H */

/* Some systems have rpc/rpc.h */
#define HAVE_RPC_H 1

/* Do we have a real-time-clock */
#define HAVE_RTC 1

/* Some systems have semtimedop */
#define HAVE_SEMTIMEDOP 1

/* Some systems define union semun */
/* #undef HAVE_SEMUN */

/* Some systems have setenv */
#define HAVE_SETENV 1

/* Some systems have setgid */
#define HAVE_SETGID 1

/* Some systems have setuid */
#define HAVE_SETUID 1

/* Some systems have shm_open */
#define HAVE_SHM_OPEN 1

/* struct spwd has sp_expire */
#define HAVE_SP_EXPIRE 1

/* struct spwd has sp_flag */
#define HAVE_SP_FLAG 1

/* struct spwd has sp_inact */
#define HAVE_SP_INACT 1

/* struct spwd has sp_warn */
#define HAVE_SP_WARN 1

/* Some systems have srand */
#define HAVE_SRAND 1

/* Some systems have srand48 */
#define HAVE_SRAND48 1

/* statvfs */
/* #undef HAVE_STATVFS */

/* Some systems have stdint.h */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Some systems have strcspn */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Some systems have strpbrk */
#define HAVE_STRPBRK 1

/* Some systems have strspn */
#define HAVE_STRSPN 1

/* Some systems have strtof */
#define HAVE_STRTOF 1

/* Some systems have strtold */
#define HAVE_STRTOLD 1

/* Some systems have strtoll */
#define HAVE_STRTOLL 1

/* Some systems have strtoull */
#define HAVE_STRTOULL 1

/* Some systems have struct timespec */
#define HAVE_STRUCT_TIMESPEC 1

/* Some systems have swab with a char * argument */
/* #undef HAVE_SWAB_CHAR */

/* Some systems have sys/bitypes.h */
#define HAVE_SYS_BITYPES_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Some systems have sys/select.h */
#define HAVE_SYS_SELECT_H 1

/* Some systems have sys/socket.h */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Some systems have sys/uio.h */
#define HAVE_SYS_UIO_H 1

/* Some systems don't have S_ISSOCK */
#define HAVE_S_ISSOCK 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Some systems have unsetenv */
#define HAVE_UNSETENV 1

/* Some systems have windows.h */
/* #undef HAVE_WINDOWS_H */

/* Some systems have winsock2.h */
/* #undef HAVE_WINSOCK2_H */

/* Some systems have extended filesystem attributes */
#define HAVE_XATTRS 1

/* Some systems have __bswap64 */
/* #undef HAVE___BSWAP64 */

/* iov_base is char * */
#define IOV_BASE_TYPE void *

/* Mingw32 environment */
/* #undef MINGW32 */

/* Some systems have swab but don't define it */
/* #undef MUST_DEFINE_SWAB */

/* Solaris 2.6 has a few missing function prototypes */
/* #undef NEED_XNET_PROTOTYPES */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Rudiments supports PCRE */
#define RUDIMENTS_HAS_PCRE 1

/* Rudiments supports SSL */
#define RUDIMENTS_HAS_SSL 1

/* Rudiments supports threads */
#define RUDIMENTS_HAS_THREADS 1

/* Compiler supports namespaces */
#define RUDIMENTS_NAMESPACE 1

/* Version */
#define RUDIMENTS_VERSION "0.30"

/* setsockopt takes a const void * on most systems */
#define SETSOCKOPT_OPTVAL_TYPE const void *

/* Most systems define signal handlers with an integer parameter */
#define SIGNAL_HANDLER_INT 1

/* Use small rather than fast code */
/* #undef SMALL_CODE */

/* SSL_read/write can use a void * parameter instead of char * */
#define SSL_VOID_PTR 1

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Some systems don't have key_t */
/* #undef key_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Some systems don't have nlink_t */
/* #undef nlink_t */

/* Some systems don't have off64_t */
/* #undef off64_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Some systems don't define socklen_t */
/* #undef socklen_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
