.TH RUDIMENTS-CONFIG "1" "September 2015" "rudiments-config" "User Commands"
.SH NAME
rudiments-config \- helper script for rudiments library
.SH SYNOPSIS
.B rudiments-config
[\fIOPTIONS\fR] 
.SH DESCRIPTION
Provides rudiments library compile flags and version information.
.TP
\fB\-\-prefix
print prefix
.TP
\fB\-\-exec\-prefix
print exec\-prefix 
.TP
\fB\-\-version
print rudiments library version
.TP
\fB\-\-libs
print libs string for compiling with rudiments
.TP
\fB\-\-with-rpath
print libs string for compiling with rudiments, including rpath (if any)
.TP
\fB\-\-cflags
print cflags
.SH AUTHOR
This manual page was written by Renat Sabitov <srr@stacksoft.ru>,
for the Debian GNU/Linux system (but may be used by others).

