#!/bin/sh

HOST=`hostname`

# "krb5" mechanism
#./gssclient -host $HOST -service gssserver -mech "{ 1 3 5 1 5 2 }" -message "krb5 mech test"

# "iakerb" mechanism
#./gssclient -host $HOST -service gssserver -mech "{ 1 3 6 1 5 2 5 }" -message "iakerb mech test"

./gssclient -host $HOST -service gssserver -message "ccount/mcount test" -ccount 20 -mcount 100 -dcount 100000
