#!/bin/sh

HOST=`hostname`

# validate server...

# negotiate protocol
./tlsclient -host $HOST -cert ./client.pem -ca ./ca.crt -ccount 5 -mcount 10 -dcount 100000

# tls 1.2
./tlsclient -host $HOST -version TLS1_2 -cert ./client.pem -ca ./ca.crt -ccount 5 -mcount 10 -dcount 100000

# tls 1.1
./tlsclient -host $HOST -version TLS1_1 -cert ./client.pem -ca ./ca.crt -ccount 5 -mcount 10 -dcount 100000

# tls 1
./tlsclient -host $HOST -version TLS1 -cert ./client.pem -ca ./ca.crt -ccount 5 -mcount 10 -dcount 100000



# don't validate server...

# negotiate protocol
./tlsclient -host $HOST -cert ./client.pem -validate no -ccount 5 -mcount 10 -dcount 100000

# tls 1.2
./tlsclient -host $HOST -version TLS1_2 -cert ./client.pem -validate no -ccount 5 -mcount 10 -dcount 100000

# tls 1.1
./tlsclient -host $HOST -version TLS1_1 -cert ./client.pem -validate no -ccount 5 -mcount 10 -dcount 100000

# tls 1
./tlsclient -host $HOST -version TLS1 -cert ./client.pem -validate no -ccount 5 -mcount 10 -dcount 100000
