const char normal[]=
"<?xml version=\"1.0\"?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<test>\n"
"	<!-- comment before test1 -->\n"
"	text before test1\n"
"	<test1 name1=\"value1\" name2=\"value2\" name3=\"value3\">\n"
"		text before test11\n"
"		<test11 name111=\"value111\">\n"
"			text inside test11\n"
"		</test11>\n"
"		text after test11\n"
"		text before test12\n"
"		<test12 name121=\"value121\">\n"
"			text inside test12\n"
"		</test12>\n"
"		text after test12\n"
"		text before test13\n"
"		<test13 name131=\"value131\"/>\n"
"		text after test13\n"
"	</test1>\n"
"	text after test1\n"
"	<!-- comment after test1 -->\n"
"	<!-- comment before test2 -->\n"
"	text before test2\n"
"	<test2 name1=\"value1\" name2=\"value2\" name3=\"value3\">\n"
"		text before test21\n"
"		<test21 name211=\"value211\">\n"
"			text inside test21\n"
"		</test21>\n"
"		text after test21\n"
"		text before test22\n"
"		<test22 name221=\"value221\">\n"
"			text inside test22\n"
"		</test22>\n"
"		text after test22\n"
"		text before test23\n"
"		<test23 name231=\"value231\"/>\n"
"		text after test23\n"
"	</test2>\n"
"	text after test2\n"
"	<!-- comment after test2 -->\n"
"</test>\n";


const char ns[]=
"<?xml version=\"1.0\"?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<testns:test>\n"
"	<!-- comment before test1 -->\n"
"	text before test1\n"
"	<testns:test1 name1=\"value1\" name2=\"value2\" name3=\"value3\">\n"
"		text before test11\n"
"		<testns:test11 name111=\"value111\">\n"
"			text inside test11\n"
"		</testns:test11>\n"
"		text after test11\n"
"		text before test12\n"
"		<testns:test12 name121=\"value121\">\n"
"			text inside test12\n"
"		</testns:test12>\n"
"		text after test12\n"
"		text before test13\n"
"		<testns:test13 name131=\"value131\"/>\n"
"		text after test13\n"
"	</testns:test1>\n"
"	text after test1\n"
"	<!-- comment after test1 -->\n"
"	<!-- comment before test2 -->\n"
"	text before test2\n"
"	<testns:test2 name1=\"value1\" name2=\"value2\" name3=\"value3\">\n"
"		text before test21\n"
"		<testns:test21 name211=\"value211\">\n"
"			text inside test21\n"
"		</testns:test21>\n"
"		text after test21\n"
"		text before test22\n"
"		<testns:test22 name221=\"value221\">\n"
"			text inside test22\n"
"		</testns:test22>\n"
"		text after test22\n"
"		text before test23\n"
"		<testns:test23 name231=\"value231\"/>\n"
"		text after test23\n"
"	</testns:test2>\n"
"	text after test2\n"
"	<!-- comment after test2 -->\n"
"</testns:test>\n";


const char escapes[]=
"<?xml version=\"1.0\"?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<test>\n"
"	<test1 name1=\"&amp;&lt;&gt;&apos;&quot;\" name2=\"&amp&lt&gt&apos&quot\" name3=\"&&&&&\"/>"
"	&amp;&lt;&gt;&apos;&quot;\n"
"	&amp&lt&gt&apos&quot\n"
"	&&&&&\n"
"</test>\n";


const char cdata[]=
"<?xml version=\"1.0\"?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<test>\n"
"	<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<![CDATA[ test [ test [ test [test]]]]]>\n"
"</test>\n";


const char target[]=
"<?xml version=\"1.0\"?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<test>\n"
"	<?target test1=\"test1\"?>\n"
"	<?target test2=\"test2\"?>\n"
"	<?target test3=\"test3\"?>\n"
"</test>\n";


const char singlequotes[]=
"<?xml version='1.0'?>\n"
//"<!DOCTYPE test SYSTEM 'test.dtd' [ test [test [test [test]]]]>\n"
"<test>\n"
"	<!-- comment before test1 -->\n"
"	text before test1\n"
"	<test1 name1='value1' name2='value2' name3='value3'>\n"
"		text before test11\n"
"		<test11 name111='value111'>\n"
"			text inside test11\n"
"		</test11>\n"
"		text after test11\n"
"		text before test12\n"
"		<test12 name121='value121'>\n"
"			text inside test12\n"
"		</test12>\n"
"		text after test12\n"
"		text before test13\n"
"		<test13 name131='value131'/>\n"
"		text after test13\n"
"	</test1>\n"
"	text after test1\n"
"	<!-- comment after test1 -->\n"
"	<!-- comment before test2 -->\n"
"	text before test2\n"
"	<test2 name1='value1' name2='value2' name3='value3'>\n"
"		text before test21\n"
"		<test21 name211='value211'>\n"
"			text inside test21\n"
"		</test21>\n"
"		text after test21\n"
"		text before test22\n"
"		<test22 name221='value221'>\n"
"			text inside test22\n"
"		</test22>\n"
"		text after test22\n"
"		text before test23\n"
"		<test23 name231='value231'/>\n"
"		text after test23\n"
"	</test2>\n"
"	text after test2\n"
"	<!-- comment after test2 -->\n"
"</test>\n";


const char oddspacing[]=
"<?xml version=\"1.0\" ?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<test >\n"
"	<!-- comment before test1 -->\n"
"	text before test1\n"
"	<test1  name1=\"value1\" name2=\"value2\"  name3=\"value3\" >\n"
"		text before test11\n"
"		<test11  name111=\"value111\" >\n"
"			text inside test11\n"
"		< / test11 >\n"
"		text after test11\n"
"		text before test12\n"
"		<test12  name121=\"value121\" >\n"
"			text inside test12\n"
"		< / test12 >\n"
"		text after test12\n"
"		text before test13\n"
"		<test13  name131=\"value131\" / >\n"
"		text after test13\n"
"	< / test1 >\n"
"	text after test1\n"
"	<!-- comment after test1 -->\n"
"	<!-- comment before test2 -->\n"
"	text before test2\n"
"	<test2  name1=\"value1\"  name2=\"value2\"  name3=\"value3\" >\n"
"		text before test21\n"
"		<test21  name211=\"value211\" >\n"
"			text inside test21\n"
"		< / test21 >\n"
"		text after test21\n"
"		text before test22\n"
"		< test22  name221=\"value221\" >\n"
"			text inside test22\n"
"		< / test22 >\n"
"		text after test22\n"
"		text before test23\n"
"		< test23  name231=\"value231\" / >\n"
"		text after test23\n"
"	< / test2 >\n"
"	text after test2\n"
"	<!-- comment after test2 -->\n"
"< / test >\n";
