const char xmls[]=
"<?xml version=\"1.0\" ?>\n"
//"<!DOCTYPE test SYSTEM \"test.dtd\" [ test [test [test [test]]]]>\n"
"<test>start test text\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"	<tag1 name11='&amp;&lt;&gt;&apos;&quot;' name12='&amp&lt&gt&apos&quot' name13='&&&&&' / > end tag1 text\n"
"	<tag2 name21=\"value21\" name22=\"value22\"> start tag2 text\n"
"		<tag3 name31=\"value31\" name32=\"value32\"> start tag3 text\n"
"			<tag4 name41=\"value41\" name42=\"value42\" /> end tag4 end text\n"
"		</tag3> end tag3 text\n"
"<!-- test comment -->\n"
"<?target test=\"test1\"?>\n"
"	</tag2> end tag2 text\n"
"&amp;&lt;&gt;&apos;&quot;\n"
"&amp&lt&gt&apos&quot\n"
"&&&&&\n"
"<![CDATA[ test [ test [ test [test]]]]]>\n"
"\n"
"<testns:testtag1>\n"
"  <testns:testtag2>\n"
"    <testns:testtag3/>\n"
"  </testns:testtag2>\n"
"</testns:testtag1>\n"
"\n"
"</test>\n";
