include ../config.mk

top_srcdir = ..
INSTALL = $(top_srcdir)/install-sh -c

install:
	$(top_srcdir)/mkinstalldirs $(incdir)/rudiments
	$(top_srcdir)/mkinstalldirs $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/client.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/commandline.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/daemonprocess.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/datatransport.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/datatransportfactory.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/datetime.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/dtd.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/errorhandler.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/file.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/filedescriptor.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/groupentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/hostentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/inetclientsocket.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/inetserversocket.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/list.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/listener.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/logger.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/memorypool.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/passwdentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/permissions.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/protocolentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/randomnumber.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/regularexpression.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/semaphoreset.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/server.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/serversocket.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/sharedmemory.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/signalclasses.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/string.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/stringbuffer.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/text.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/unixclientsocket.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/unixserversocket.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/variablebuffer.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/xmlsax.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/xmldom.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/xmldomnode.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/client.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/commandline.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/commandlineinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/config.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/daemonprocess.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/daemonprocessinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/datatransport.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/datatransportinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/datetime.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/datetimeinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/dtd.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/dtdinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/errorhandler.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/errorhandlerinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/file.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/fileinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/filedestination.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/filedescriptor.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/groupentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/groupentryinlines.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/hostentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/hostentryinlines.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/inetsocket.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/inetsocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/inetclientsocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/inetserversocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/list.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/listinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/listnode.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/listnodeinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/listener.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/listenerinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/logdestination.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/logger.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/loggerinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/memorypool.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/memorypoolinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/memorypoolnode.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/passwdentry.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/passwdentryinlines.h $(incdir)/rudiments
	$(INSTALL) -m 644 rudiments/private/permissionsinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/protocolentry.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/protocolentryinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/randomnumberinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/regularexpression.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/regularexpressioninlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/semaphoreset.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/semaphoresetinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/serverinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/serversocket.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/serversocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/sharedmemory.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/sharedmemoryinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/signalclassesinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/signalhandler.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/signalset.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/stderrdestination.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/stdoutdestination.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/string.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/stringinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/stringbuffer.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/stringbufferinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/syslogdestination.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/text.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/textinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/unixclientsocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/unixserversocket.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/unixserversocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/unixsocket.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/unixsocketinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/variablebuffer.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/variablebufferinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/xmlsax.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/xmlsaxinlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/xmldom.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/xmldominlines.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/xmldomnode.h $(incdir)/rudiments/private
	$(INSTALL) -m 644 rudiments/private/xmldomnodeinlines.h $(incdir)/rudiments/private

uninstall:
	$(RM) $(incdir)/client.h
	$(RM) $(incdir)/clientsocket.h
	$(RM) $(incdir)/commandline.h
	$(RM) $(incdir)/daemon.h
	$(RM) $(incdir)/daemonprocess.h
	$(RM) $(incdir)/datetime.h
	$(RM) $(incdir)/genericsocket.h
	$(RM) $(incdir)/permissions.h
	$(RM) $(incdir)/randomnumber.h
	$(RM) $(incdir)/regularexpression.h
	$(RM) $(incdir)/semaphoreset.h
	$(RM) $(incdir)/server.h
	$(RM) $(incdir)/serverpool.h
	$(RM) $(incdir)/serversocketpool.h
	$(RM) $(incdir)/serversocket.h
	$(RM) $(incdir)/sharedmemory.h
	$(RM) $(incdir)/signalclasses.h
	$(RM) $(incdir)/text.h
	$(RM) $(incdir)/trim.h
	$(RM) $(incdir)/encoding.h
	$(RM) $(incdir)/casechange.h
	$(RM) $(incdir)/private/client.h
	$(RM) $(incdir)/private/clientsocket.h
	$(RM) $(incdir)/private/commandline.h
	$(RM) $(incdir)/private/daemon.h
	$(RM) $(incdir)/private/daemonprocess.h
	$(RM) $(incdir)/private/genericsocket.h
	$(RM) $(incdir)/private/randomnumber.h
	$(RM) $(incdir)/private/regularexpression.h
	$(RM) $(incdir)/private/semaphoreset.h
	$(RM) $(incdir)/private/sharedmemory.h
	$(RM) $(incdir)/private/server.h
	$(RM) $(incdir)/private/serverpool.h
	$(RM) $(incdir)/private/serversocketpool.h
	$(RM) $(incdir)/private/serversocket.h
	$(RM) $(incdir)/private/signalhandler.h
	$(RM) $(incdir)/private/signalset.h
	$(RM) $(incdir)/private/datetime.h
	$(RMTREE) $(incdir)/rudiments
